workflows:
  ios-workflow:
    name: iOS Build & Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.migambi.netflex
      vars:
        APP_ID: "com.migambi.netflex"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Set up keychain to be beautiful
        script: |
          keychain initialize
      - name: Set up code signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Create export options
        script: |
          cat > /Users/builder/export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>destination</key>
              <string>export</string>
              <key>method</key>
              <string>app-store-connect</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
      - name: Fluxo de dependências
        script: |
          flutter packages pub get
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
          echo "IPA location:"
          find build -name "*.ipa" -type f
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - "**/*.ipa"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true