workflows:
  ios-workflow:
    name: iOS Build & Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic Key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.migambi.netflex
      vars:
        APP_ID: "com.migambi.netflex"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    scripts:
      - name: Set up keychain to be beautiful
        script: |
          keychain initialize
      - name: Set up code signing
        script: |
          keychain add-certificates
      - name: Fluxo de dependências
        script: |
          flutter packages pub get
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration